### ISSUE TITLE
Define type without inheriting all default attributes

### ISSUE THREAD

**Issue by justahero** [Asquera/elasticsearch-rake-tasks#10]
As a user I would like to define a default mapping for some types, but not necessarily for all. Example: types `user` & `company` share the same properties like `name`, `address`, etc, the type `comment` does not need those default properties.

Unless there is a native way that I'm missing I would propose a specific keyword to add to the top of the yaml mapping file

``` yaml

---
inherit: false
properties:
  name:
    type: string
```

The keyword `inherit` can then be filtered when generating the JSON request (mapping) for the template API.
